### ISSUE TITLE
Roadmap to Clarinet 1.0

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/clarinet#107]
Creating a quick issue aiming at tracking the acceptance criteria which will move Clarinet from a `0.x` to a `1.x`.

Features:
- [x] NPM wrapper library that can drive Devnet (related https://github.com/hirosystems/clarinet/issues/43), that can be used for writing FULL end to end integration tests.

Internals:
- [ ] https://github.com/hirosystems/clarinet/issues/90
- [ ] https://github.com/hirosystems/clarinet/issues/38
- [ ] https://github.com/hirosystems/clarinet/issues/91
- [x] https://github.com/hirosystems/clarinet/issues/82
- [x] https://github.com/hirosystems/clarinet/issues/81
- [x] https://github.com/hirosystems/clarinet/issues/112
- [x] https://github.com/hirosystems/clarinet/issues/111

REPL:
- [ ] https://github.com/hirosystems/clarity-repl/issues/22
- [x] https://github.com/hirosystems/clarity-repl/issues/18

**Comment by lgalabru** [comment]
This issue is probably useless, now that we're tracking the `1.0` issues with a tag.
Closing now.
